version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlnweb
    ports:
      - "3002:80"   # host:container (host=3002, container=80)
    restart: unless-stopped


